# Generated by Django 4.2.30 on 2026-08-05 06:50

from django.db import migrations


PROMPTS = [
    {
        'title': 'Design a URL Shortener',
        'description': 'Build a service that converts long links into short, shareable URLs at scale.',
        'difficulty': 'beginner',
    },
    {
        'title': 'Design a Chat Application',
        'description': 'Design real-time messaging for individual and group conversations.',
        'difficulty': 'intermediate',
    },
    {
        'title': 'Design an Instagram Feed',
        'description': 'Plan how users upload content and view a personalized feed.',
        'difficulty': 'advanced',
    },
]


def add_prompts(apps, schema_editor):
    Prompt = apps.get_model('testApp', 'Prompt')
    for prompt in PROMPTS:
        Prompt.objects.get_or_create(title=prompt['title'], defaults=prompt)


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_prompts, migrations.RunPython.noop),
    ]
